const labels: Record<string, string> = {
  lol_pc: "英雄联盟",
  tft: "云顶之弈",
  lol_esports: "英雄联盟电竞",
  lol_universe: "符文之地",
  other_lol_product: "其他 LoL 产品",
  riot_ecosystem: "拳头生态",
  unknown: "未分类",
  esports: "电竞",
  other_products: "其他产品",
  ecosystem: "生态",
  developing: "持续发展",
  confirmed: "已经确认",
  denied: "已经否认",
  disputed: "存在争议",
  stale: "暂时沉寂",
  resolved: "已经结束",
  unconfirmed: "尚未确认",
  officially_confirmed: "官方确认",
  corroborated: "多源印证",
  plausible: "具备依据",
  unverified: "尚未核验",
  critical: "关键",
  high: "高",
  medium: "中",
  low: "低",
  cold: "低热度",
  emerging: "正在升温",
  active: "活跃",
  hot: "热门",
  surging: "快速上升",
  gameplay_balance: "玩法平衡",
  gameplay_release: "玩法发布",
  cosmetic_release: "外观发布",
  player_activity: "玩家活动",
  commercial_offer: "商业活动",
  service_incident: "服务异常",
  security_enforcement: "安全治理",
  esports_match: "电竞赛况",
  esports_schedule: "电竞赛程",
  roster_change: "阵容变动",
  esports_rules: "赛事规则",
  universe_release: "宇宙内容",
  media_release: "媒体内容",
  corporate_change: "公司动态",
  platform_service: "平台服务",
  other_named_development: "其他进展",
  reports: "报道",
  supports: "支持",
  confirms: "确认",
  denies: "否认",
  corrects: "更正",
  mentions: "提及",
  responsible_official: "责任方官方",
  direct_subject: "直接当事方",
  first_party_participant: "一手参与者",
  independent_media: "独立媒体",
  known_leaker: "已知爆料者",
  ordinary_account: "普通账号",
  republisher: "转发来源",
  material_update: "实质进展",
  corroboration_only: "补充印证",
  duplicate: "重复信息",
  context_only: "背景信息",
  game_patch_notes: "版本说明",
  game_official_preview: "官方预览",
  game_announcement: "游戏公告",
  game_notice: "游戏通知",
  game_promotion_interaction: "游戏推广互动",
  game_community_notice: "社区通知",
  game_community_promotion_interaction: "社区推广互动",
  game_leak: "游戏爆料",
  game_community_discussion: "社区讨论",
  esports_announcement: "电竞公告",
  esports_promotion_interaction: "电竞推广互动",
  esports_rumor_speculation: "电竞传闻",
  esports_community_discussion: "电竞社区讨论",
  lol_universe_announcement: "宇宙内容公告",
  lol_universe_promotion_interaction: "宇宙内容推广",
  lol_universe_leak: "宇宙内容爆料",
  lol_universe_community_discussion: "宇宙内容讨论",
  other_lol_product_announcement: "其他产品公告",
  other_lol_product_promotion_interaction: "其他产品推广",
  other_lol_product_leak: "其他产品爆料",
  other_lol_product_community_discussion: "其他产品讨论",
  riot_ecosystem_announcement: "拳头生态公告",
  riot_ecosystem_promotion_interaction: "拳头生态推广",
  riot_ecosystem_leak: "拳头生态爆料",
  riot_ecosystem_community_discussion: "拳头生态讨论",
  balance_gameplay: "平衡与玩法",
  champions: "英雄",
  items_runes_systems: "装备、符文与系统",
  game_modes: "游戏模式",
  gameplay: "玩法",
  service_technical: "服务与技术",
  cosmetics: "外观内容",
  shop_monetization: "商城与商业化",
  activities_rewards: "活动与奖励",
  security_fair_play: "安全与公平竞技",
  community: "社区",
  guides_education: "攻略与教学",
  tft_gameplay: "云顶玩法",
  esports_competition: "电竞赛事",
  esports_rosters: "电竞阵容",
  esports_analysis: "电竞分析",
  esports_broadcast: "电竞直播",
  esports_fandom_live: "电竞互动",
  lore_universe: "世界观",
  media_entertainment: "媒体与娱乐",
  merchandise_collectibles: "商品与收藏",
  corporate_partnerships: "公司与合作",
  platform_services: "平台服务",
};

export function publicLabel(value: string): string {
  return labels[value] ?? value.replaceAll("_", " ");
}

export function formatPublicTime(value: string | null): string {
  if (!value) return "时间待确认";
  return new Intl.DateTimeFormat("zh-CN", {
    timeZone: "Asia/Shanghai",
    month: "numeric",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}
