"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { adminApi } from "@/lib/api";
import type { PipelineCorrection, PipelineJob } from "@/lib/types";
import { PipelineJobRow } from "@/components/admin/PipelineJobRow";
import { PaginationControls } from "@/components/admin/PaginationControls";
import { relativeTime } from "@/components/admin/admin-utils";

export default function SystemPage() {
  const [jobs, setJobs] = useState<PipelineJob[]>([]); const [corrections, setCorrections] = useState<PipelineCorrection[]>([]); const [errors, setErrors] = useState<string[]>([]); const [loading, setLoading] = useState(true);
  const [jobPage, setJobPage] = useState(1); const [correctionPage, setCorrectionPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [jobSort, setJobSort] = useState<"asc" | "desc">("desc"); const [correctionSort, setCorrectionSort] = useState<"asc" | "desc">("desc");
  const load = useCallback(async () => { setLoading(true); const results = await Promise.allSettled([adminApi<PipelineJob[]>("/pipeline/jobs"), adminApi<PipelineCorrection[]>("/pipeline/corrections")]); const next: string[] = []; if (results[0].status === "fulfilled") setJobs(results[0].value); else next.push("Pipeline jobs 加载失败"); if (results[1].status === "fulfilled") setCorrections(results[1].value); else next.push("Corrections 加载失败"); setErrors(next); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const counts = useMemo(() => Object.fromEntries(["running", "queued", "completed", "failed"].map((status) => [status, jobs.filter((job) => job.status === status).length])), [jobs]);
  const failed = useMemo(() => jobs.filter((job) => job.status === "failed").sort((left, right) => (jobSort === "desc" ? -1 : 1) * left.created_at.localeCompare(right.created_at)), [jobSort, jobs]);
  const orderedCorrections = useMemo(() => [...corrections].sort((left, right) => (correctionSort === "desc" ? -1 : 1) * left.requested_at.localeCompare(right.requested_at)), [correctionSort, corrections]);
  const failedPage = failed.slice((jobPage - 1) * pageSize, jobPage * pageSize); const correctionRows = orderedCorrections.slice((correctionPage - 1) * pageSize, correctionPage * pageSize);
  return <div className="admin-page"><header className="admin-page-head"><div><span className="admin-eyebrow">OPERATIONS</span><h1>系统运维</h1><p>追踪 PipelineJob 队列、失败恢复与阶段修正记录。</p></div></header>{errors.map((error) => <div className="admin-error-state" key={error}><span>{error}</span><button onClick={() => void load()}>重试</button></div>)}<section className="admin-metrics"><div><span>运行中</span><strong>{counts.running ?? 0}</strong></div><div><span>等待</span><strong>{counts.queued ?? 0}</strong></div><div><span>完成</span><strong>{counts.completed ?? 0}</strong></div><div className={failed.length ? "danger" : ""}><span>失败</span><strong>{failed.length}</strong></div></section><section className="admin-panel"><div className="admin-section-title"><h2>失败任务</h2><span>{failed.length} 条</span></div>{loading ? <div className="admin-skeleton admin-skeleton-table" /> : failed.length ? <><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Job ID</th><th>Raw Item</th><th>失败阶段</th><th>错误摘要</th><th>操作</th></tr></thead><tbody>{failedPage.map((job) => <PipelineJobRow key={job.id} job={job} onRecovered={() => void load()} />)}</tbody></table></div><PaginationControls page={jobPage} pageSize={pageSize} total={failed.length} sort={jobSort} onPageChange={setJobPage} onPageSizeChange={(value) => { setPageSize(value); setJobPage(1); setCorrectionPage(1); }} onSortChange={(value) => { setJobSort(value); setJobPage(1); }} /></> : <div className="admin-empty">当前没有失败任务。</div>}</section><section className="admin-panel"><div className="admin-section-title"><h2>Pipeline Corrections</h2><span>{corrections.length} 条</span></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>时间</th><th>Raw Item</th><th>重启阶段</th><th>恢复模式</th><th>原因</th><th>状态</th></tr></thead><tbody>{correctionRows.map((correction) => <tr key={correction.id}><td title={new Date(correction.requested_at).toLocaleString("zh-CN")}>{relativeTime(correction.requested_at)}</td><td className="admin-number">#{correction.raw_item_id}</td><td><span className="admin-badge">{correction.restart_from_stage}</span></td><td>{correction.resume_mode}</td><td>{correction.reason}</td><td><span className={`admin-badge ${correction.status === "failed" ? "danger" : correction.status === "completed" ? "success" : ""}`}>{correction.status}</span></td></tr>)}</tbody></table></div><PaginationControls page={correctionPage} pageSize={pageSize} total={corrections.length} sort={correctionSort} onPageChange={setCorrectionPage} onPageSizeChange={(value) => { setPageSize(value); setJobPage(1); setCorrectionPage(1); }} onSortChange={(value) => { setCorrectionSort(value); setCorrectionPage(1); }} /></section></div>;
}
